import commonjs from "@rollup/plugin-commonjs"
import { nodeResolve } from "@rollup/plugin-node-resolve"
import typescript from "@rollup/plugin-typescript"
import copy from "rollup-plugin-copy"

const distDir = "dist"
const docsPlugin = "docs/.obsidian/plugins/temple-reborn/"
const isProd = process.env.BUILD === "production"

const banner = `
/* THIS IS A GENERATED/BUNDLED FILE BY ROLLUP! */
/* https://github.com/Larandar/Temple-Reborn */
`

const buildOutput = (dir, isProd) => {
    return {
        dir: dir,
        sourcemap: "inline",
        sourcemapExcludeSources: isProd,
        format: "cjs",
        exports: "default",
        banner,
    }
}

export default {
    input: "src/main.ts",
    output: [buildOutput(distDir, isProd), buildOutput(docsPlugin, false)],
    clearScreen: true,
    external: ["obsidian"],
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        copy({
            copyOnce: false,
            targets: [
                { src: "src/styles.css", dest: [distDir, docsPlugin] },
                { src: "manifest.json", dest: [distDir, docsPlugin] },
            ],
        }),
    ],
}
