import commonjs from "@rollup/plugin-commonjs";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";
import copy from "rollup-plugin-copy";

const distDir = "dist";
const isProd = process.env.BUILD === "production";

const banner = `
/* THIS IS A GENERATED/BUNDLED FILE BY ROLLUP! */
/* https://github.com/Larandar/Temple-Reborn */
`;

export default {
  input: "src/main.ts",
  output: {
    dir: distDir,
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    typescript(),
    nodeResolve({ browser: true }),
    commonjs(),
    copy({
      copyOnce: false,
      targets: [
        { src: "src/styles.css", dest: distDir },
        { src: "manifest.json", dest: distDir },
      ],
    }),
  ],
};
